build-ansible-collection-pod: avoid ansible_user_dir
Well, even with ansible_user_dir empty, we end up with

```
ERROR: Invalid requirement: '/src/github.com/ansible-network/releases'
Hint: It looks like a path. File '/src/github.com/ansible-network/releases' does not exist.
```