AWX: skip unprotected branch
This change should prevent MERGER_FAILURE caused by awx feature branch workflow
that may results in:

  ValueError: Could not parse git-remote prune result:
    ' refs/remotes/origin/HEAD will become dangling!'